### ISSUE TITLE
MaharaDroid 2.0.1 crashes when you launch the camera via the app

### ISSUE THREAD

**Issue by agwells** [MaharaProject/maharadroid#2]
Reported to the Google Play account:

Application version: 2.0.11
Android version: Android 4.41
Device: G2 MINI (g2m)

java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=10292, uid=10269 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1465)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
at android.content.ContentProviderProxy.insert(ContentProviderNative.java:468)
at android.content.ContentResolver.insert(ContentResolver.java:1206)
at nz.net.catalyst.MaharaDroid.Utils.makeCameraIntent(Utils.java:208)
at nz.net.catalyst.MaharaDroid.ui.ArtefactExpandableListAdapterActivity.onOptionsItemSelected(ArtefactExpandableListAdapterActivity.java:232)
at android.app.Activity.onMenuItemSelected(Activity.java:2644)
at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1095)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:744)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:883)
at com.android.internal.view.menu.IconMenuView.invokeItem(IconMenuView.java:468)
at com.android.internal.view.menu.IconMenuItemView.performClick(IconMenuItemView.java:126)
at android.view.View$PerformClick.run(View.java:18473)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)

**Comment by agwells** [comment]
To replicate:

1. Launch the MaharaDroid app
2. Top the "Start" button
3. Tap the "Camera" button

Expected result: System camera app should open
Actual result: "Unfortunately, MaharaDroid has stopped"

**Comment by agwells** [comment]
Fixed.
