### ISSUE TITLE
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/40763 from pid=18326, uid=10114 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

### ISSUE THREAD

**Issue by agwells** [MaharaProject/maharadroid#3]
Application version: 1.8
Android version: 4.4

java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/40763 from pid=18326, uid=10114 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1465)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:413)
at android.content.ContentResolver.query(ContentResolver.java:464)
at android.content.ContentResolver.query(ContentResolver.java:407)
at nz.net.catalyst.MaharaDroid.Utils.getFilePath(Utils.java:91)
at nz.net.catalyst.MaharaDroid.ui.ArtifactSettingsActivity.InitiateUpload(ArtifactSettingsActivity.java:214)
at nz.net.catalyst.MaharaDroid.ui.ArtifactSettingsActivity.onClick(ArtifactSettingsActivity.java:189)
at android.view.View.performClick(View.java:4442)
at android.view.View$PerformClick.run(View.java:18473)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)

**Comment by agwells** [comment]
Just wanted to record this one for posterity. Scott fixed it by adding the "READ_EXTERNAL_STORAGE" permission to the app manifest. This fix was included in version 2.0.1.
